services:
  antibruteforce-test:
    build:
      context: ./..
      dockerfile: ./deployment/Dockerfile.test
    ports:
      - "8000:8000"
    environment:
      - LISTEN=0.0.0.0:8000
      - LIMIT_LOGIN=10
      - LIMIT_PASSWORD=100
      - LIMIT_IP=1000
      - REDIS_DSN=redis:6379
    depends_on:
      redis:
        condition: service_healthy
    command: ["go", "test", "-race", "-v", "-count=1", "./...", "--tags", "integration"]

  redis:
    image: redis:6-alpine3.16
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
